### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by zxzhijia** [soumith/cvpr2015#11]
How long it takes for running that 60 minutes tutorial example? My CPU is intel i7 3.4 Hz 3.4 Hz. GPU is  NVIDIA GeForce GTX 750 Ti.

**Comment by soumith** [comment]
it takes a few seconds to a minute ish. shouldn't take longer than that.

**Comment by zxzhijia** [comment]
it's really strange. It's been running an hour on my PC. I don't know why.

**Comment by zxzhijia** [comment]
I guess I get almost exactly the same problem as tohnperfect got before. He had a long discussion with you. But I don't know how to solve it. 

https://github.com/facebook/iTorch/issues/5

**Comment by zxzhijia** [comment]
seems slightly different. You asked him how long it takes for commend: itorch; torch.randn(10). He said forever. But mine is very fast. But only "trainer:train(trainset)" takes forever. What's the output of that commend?

**Comment by zxzhijia** [comment]
It works fine now when I run it on GPU. Thanks.

**Comment by soumith** [comment]
hi Xu, I really suspect now that your CPU torch was not installed with good BLAS support. I suggest checking your output of your torch install and seeing if it links against a blas library.

**Comment by zxzhijia** [comment]
Sorry, I'm beginner. how to check that?

**Comment by zxzhijia** [comment]
Should I install OpenBLAS?

**Comment by zxzhijia** [comment]
I installed OpenBLAS by your comments in another link. 

git clone https://github.com/xianyi/OpenBLAS.git
cd OpenBLAS
make NO_AFFINITY=1 USE_OPENMP=1
sudo make install

But it still doesn't work for CPU. Is anything that may help? Thanks.

**Comment by zxzhijia** [comment]
Below is the information I found in my install.log for torch. 

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found readline library
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for sin in m
-- Looking for sin in m - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test LJ_TARGET_X64
-- Performing Test LJ_TARGET_X64 - Success
-- LuaJIT Target: x64
-- LuaJIT target x64
-- Performing Test LJ_ARCH_BITS_64
-- Performing Test LJ_ARCH_BITS_64 - Success
-- Performing Test LJ_HASJIT_1
-- Performing Test LJ_HASJIT_1 - Success
-- Performing Test LJ_HASFFI_1
-- Performing Test LJ_HASFFI_1 - Success
-- Performing Test LJ_DUALNUM_1
-- Performing Test LJ_DUALNUM_1 - Failed
-- Performing Test LJ_ARCH_HASFPU_1
-- Performing Test LJ_ARCH_HASFPU_1 - Success
-- Performing Test LJ_ABI_SOFTFP_1
-- Performing Test LJ_ABI_SOFTFP_1 - Failed
-- Looking for sin in m
-- Looking for sin in m - found
-- Found Wget: /usr/bin/wget  
-- Found MD5: /usr/bin/md5sum  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xu/MYDIR/torch/build
Scanning dependencies of target minilua
[  3%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/minilua.dir/src/host/minilua.c.o
Linking C executable minilua
[  3%] Built target minilua
[  7%] Generating buildvm_arch.h
Scanning dependencies of target buildvm
[ 11%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm.c.o
[ 15%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_asm.c.o
[ 19%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_peobj.c.o
[ 23%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_lib.c.o
[ 26%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_fold.c.o
Linking C executable buildvm
[ 26%] Built target buildvm
[ 30%] Generating vmdef.lua
[ 34%] Generating lj_vm.S
[ 38%] Generating lj_ffdef.h
[ 42%] Generating lj_bcdef.h
[ 46%] Generating lj_libdef.h
[ 50%] Generating lj_recdef.h
[ 53%] Generating lj_folddef.h
Scanning dependencies of target libluajit
[ 57%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/src/ljamalg.c.o
[ 61%] Building ASM object exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/lj_vm.S.o
Linking C shared library libluajit.so
[ 61%] Built target libluajit
Scanning dependencies of target luajit
[ 65%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/src/luajit.c.o
[ 69%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/src/ljamalg.c.o
[ 73%] Building ASM object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/lj_vm.S.o
Linking C executable luajit
[100%] Built target luajit
[  3%] Built target minilua
[ 26%] Built target buildvm
[ 61%] Built target libluajit
[100%] Built target luajit
Install the project...
-- Install configuration: "Release"
-- Installing: /home/xu/MYDIR/torch/install/include/luaconf.h
-- Installing: /home/xu/MYDIR/torch/install/include/lua.h
-- Installing: /home/xu/MYDIR/torch/install/include/lauxlib.h
-- Installing: /home/xu/MYDIR/torch/install/include/lualib.h
-- Installing: /home/xu/MYDIR/torch/install/include/lua.hpp
-- Installing: /home/xu/MYDIR/torch/install/include/luajit.h
-- Installing: /home/xu/MYDIR/torch/install/lib/libluajit.so
-- Installing: /home/xu/MYDIR/torch/install/bin/luajit
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/bc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/v.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dump.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_x86.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_x64.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_arm.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_ppc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_mips.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_mipsel.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/bcsave.lua
-- Up-to-date: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/bc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/p.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/zone.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/vmdef.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/cfg.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/lint.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/remove.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/path_cmd.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/path.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/require.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git_https.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg_http.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg_ssh.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git_http.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/sscm.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git_file.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/svn.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg_https.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/cvs.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/purge.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/tools/patch.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/tools/tar.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/tools/zip.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/persist.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/cache.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/make.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/show.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/doc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/deps.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/dir.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/validate.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/pack.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/command_line.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/write_rockspec.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/search.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/list.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/unpack.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/loader.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/refresh_cache.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/install.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/config_cmd.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/upload/multipart.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/upload/api.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/new_version.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/add.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/util.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/index.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/manif.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/type_check.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/download.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/manif_core.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/upload.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/make_manifest.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/admin_remove.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/make.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/cmake.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/command.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/builtin.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/repos.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/help.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/unix/tools.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/win32.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/unix.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/lua.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/win32/tools.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/site_config.lua
-- Installing: /home/xu/MYDIR/torch/install/etc/luarocks/config.lua
-- Installing: /home/xu/MYDIR/torch/install/bin/luarocks
-- Installing: /home/xu/MYDIR/torch/install/bin/luarocks-admin

**Comment by zxzhijia** [comment]
`-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found readline library
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for sin in m
-- Looking for sin in m - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test LJ_TARGET_X64
-- Performing Test LJ_TARGET_X64 - Success
-- LuaJIT Target: x64
-- LuaJIT target x64
-- Performing Test LJ_ARCH_BITS_64
-- Performing Test LJ_ARCH_BITS_64 - Success
-- Performing Test LJ_HASJIT_1
-- Performing Test LJ_HASJIT_1 - Success
-- Performing Test LJ_HASFFI_1
-- Performing Test LJ_HASFFI_1 - Success
-- Performing Test LJ_DUALNUM_1
-- Performing Test LJ_DUALNUM_1 - Failed
-- Performing Test LJ_ARCH_HASFPU_1
-- Performing Test LJ_ARCH_HASFPU_1 - Success
-- Performing Test LJ_ABI_SOFTFP_1
-- Performing Test LJ_ABI_SOFTFP_1 - Failed
-- Looking for sin in m
-- Looking for sin in m - found
-- Found Wget: /usr/bin/wget  
-- Found MD5: /usr/bin/md5sum  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xu/MYDIR/torch/build
Scanning dependencies of target minilua
[  3%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/minilua.dir/src/host/minilua.c.o
Linking C executable minilua
[  3%] Built target minilua
[  7%] Generating buildvm_arch.h
Scanning dependencies of target buildvm
[ 11%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm.c.o
[ 15%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_asm.c.o
[ 19%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_peobj.c.o
[ 23%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_lib.c.o
[ 26%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_fold.c.o
Linking C executable buildvm
[ 26%] Built target buildvm
[ 30%] Generating vmdef.lua
[ 34%] Generating lj_vm.S
[ 38%] Generating lj_ffdef.h
[ 42%] Generating lj_bcdef.h
[ 46%] Generating lj_libdef.h
[ 50%] Generating lj_recdef.h
[ 53%] Generating lj_folddef.h
Scanning dependencies of target libluajit
[ 57%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/src/ljamalg.c.o
[ 61%] Building ASM object exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/lj_vm.S.o
Linking C shared library libluajit.so
[ 61%] Built target libluajit
Scanning dependencies of target luajit
[ 65%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/src/luajit.c.o
[ 69%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/src/ljamalg.c.o
[ 73%] Building ASM object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/lj_vm.S.o
Linking C executable luajit
[100%] Built target luajit
[  3%] Built target minilua
[ 26%] Built target buildvm
[ 61%] Built target libluajit
[100%] Built target luajit
Install the project...
-- Install configuration: "Release"
-- Installing: /home/xu/MYDIR/torch/install/include/luaconf.h
-- Installing: /home/xu/MYDIR/torch/install/include/lua.h
-- Installing: /home/xu/MYDIR/torch/install/include/lauxlib.h
-- Installing: /home/xu/MYDIR/torch/install/include/lualib.h
-- Installing: /home/xu/MYDIR/torch/install/include/lua.hpp
-- Installing: /home/xu/MYDIR/torch/install/include/luajit.h
-- Installing: /home/xu/MYDIR/torch/install/lib/libluajit.so
-- Installing: /home/xu/MYDIR/torch/install/bin/luajit
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/bc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/v.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dump.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_x86.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_x64.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_arm.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_ppc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_mips.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/dis_mipsel.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/bcsave.lua
-- Up-to-date: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/bc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/p.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/zone.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/jit/vmdef.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/cfg.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/lint.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/remove.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/path_cmd.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/path.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/require.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git_https.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg_http.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg_ssh.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git_http.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/sscm.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git_file.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/git.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/svn.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/hg_https.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch/cvs.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/purge.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/tools/patch.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/tools/tar.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/tools/zip.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/persist.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/cache.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/make.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/show.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/doc.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fetch.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/deps.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/dir.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/validate.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/pack.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/command_line.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/write_rockspec.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/search.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/list.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/unpack.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/loader.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/refresh_cache.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/install.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/config_cmd.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/upload/multipart.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/upload/api.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/new_version.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/add.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/util.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/index.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/manif.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/type_check.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/download.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/manif_core.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/upload.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/make_manifest.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/admin_remove.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/make.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/cmake.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/command.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/build/builtin.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/repos.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/help.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/unix/tools.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/win32.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/unix.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/lua.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/fs/win32/tools.lua
-- Installing: /home/xu/MYDIR/torch/install/share/lua/5.1/luarocks/site_config.lua
-- Installing: /home/xu/MYDIR/torch/install/etc/luarocks/config.lua
-- Installing: /home/xu/MYDIR/torch/install/bin/luarocks
-- Installing: /home/xu/MYDIR/torch/install/bin/luarocks-admin`

**Comment by soumith** [comment]
okay good, now that you installed openblas, reinstall just the torch package like this:

``` bash
export CMAKE_LIBRARY_PATH=/opt/OpenBLAS/include:/opt/OpenBLAS/lib:$CMAKE_LIBRARY_PATH
luarocks install torch
```

After that, see if things get faster :)

**Comment by zxzhijia** [comment]
xu@xu-ThinkCentre-M72e:/$ export CMAKE_LIBRARY_PATH=/opt/OpenBLAS/include:/opt/
xu@xu-ThinkCentre-M72e:/$ OpenBLAS/lib:$CMAKE_LIBRARY_PATH
bash: OpenBLAS/lib:/opt/OpenBLAS/include:/opt/: No such file or directory

**Comment by zxzhijia** [comment]
sorry. I type the wrong commend. I'll try again. Thanks.

**Comment by zxzhijia** [comment]
Wow. Amazing. Problem solved. Thanks a lot.
