### ISSUE TITLE
Displays nothing

### ISSUE THREAD

**Issue by zxzhijia** [soumith/cvpr2015#12]
When I run graph.dot(mlp.fg, 'MLP','MLP'), it displays nothing in itorch notebook. Any suggestions how to fix this?

**Comment by zxzhijia** [comment]
Problem answered by you in google Groups. Thanks again.

**Comment by soumith** [comment]
now to display, i have simplified things further.
If you reinstall itorch via: `luarocks install itorch`

Then now you can do:

``` lua
graph.dot(mlp.fg, 'MLP','MLP')
itorch.image('MLP.svg')
```

it looks much better this way.

**Comment by zxzhijia** [comment]
Thank you. But this type of install seems doesn't work for me. It says no
permission.

On Thu, Apr 14, 2016 at 12:56 AM, Soumith Chintala <notifications@github.com

**Comment by zxzhijia** [comment]
luarocks install torch works. but luarocks install itorch needs permission.
Any other way to reinstall?
