### ISSUE TITLE
(Just a doubt..!?) How to create a .t7 model from scratch(raw images & labels)?

### ISSUE THREAD

**Issue by sowjanya143** [soumith/cvpr2015#3]

**Comment by soumith** [comment]
the CIFAR dataset is provided in a special binary format
http://www.cs.toronto.edu/~kriz/cifar.html

This script converts the CIFAR dataset into .t7
https://github.com/soumith/cifar.torch

**Comment by Naresh07413** [comment]
Did u found any solution..Sowjanya?
