### ISSUE TITLE
Tutorial fails on the last line when trying to train with GPU

### ISSUE THREAD

**Issue by RobSalzwedel** [soumith/cvpr2015#5]
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h4 id="cunn:-neural-networks-on-GPUs-using-CUDA">cunn: neural networks on GPUs using CUDA<a class="anchor-link" href="#cunn:-neural-networks-on-GPUs-using-CUDA">&#182;</a></h4>

<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[60]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-lua"><pre><span class="nb">require</span> <span class="s1">&#39;</span><span class="s">cunn&#39;</span><span class="p">;</span>
</pre></div>

<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>

<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>The idea is pretty simple. Take a neural network, and transfer it over to GPU:</p>

<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[61]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-lua"><pre><span class="n">net</span> <span class="o">=</span> <span class="n">net</span><span class="p">:</span><span class="n">cuda</span><span class="p">()</span>
</pre></div>

<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>

<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>Also, transfer the criterion to GPU:</p>

<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[62]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-lua"><pre><span class="n">criterion</span> <span class="o">=</span> <span class="n">criterion</span><span class="p">:</span><span class="n">cuda</span><span class="p">()</span>
</pre></div>

<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>

<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>Ok, now the data:</p>

<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[63]:</div>
<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-lua"><pre><span class="n">trainset</span><span class="p">.</span><span class="n">data</span> <span class="o">=</span> <span class="n">trainset</span><span class="p">.</span><span class="n">data</span><span class="p">:</span><span class="n">cuda</span><span class="p">()</span>
</pre></div>

<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>

<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>Okay, let's train on GPU :) #sosimple</p>

<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[64]:</div>

<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-lua"><pre><span class="n">trainer</span> <span class="o">=</span> <span class="n">nn</span><span class="p">.</span><span class="n">StochasticGradient</span><span class="p">(</span><span class="n">net</span><span class="p">,</span> <span class="n">criterion</span><span class="p">)</span>
<span class="n">trainer</span><span class="p">.</span><span class="n">learningRate</span> <span class="o">=</span> <span class="mf">0.001</span>
<span class="n">trainer</span><span class="p">.</span><span class="n">maxIteration</span> <span class="o">=</span> <span class="mi">5</span> <span class="c1">-- just do 5 epochs of training.</span>
</pre></div>

<div class="cell border-box-sizing code_cell rendered">
<div class="input">
<div class="prompt input_prompt">In&nbsp;[65]:</div>

<div class="inner_cell">
    <div class="input_area">
<div class=" highlight hl-lua"><pre><span class="n">trainer</span><span class="p">:</span><span class="n">train</span><span class="p">(</span><span class="n">trainset</span><span class="p">)</span>
</pre></div>

<div class="output_wrapper">
<div class="output">

<div class="output_area"><div class="prompt output_prompt">Out[65]:</div>

<div class="output_text output_subarea output_execute_result">
<pre># StochasticGradient: training 
</pre>

<div class="output_area"><div class="prompt"></div>

<div class="output_subarea output_text output_error">

<pre>
...rs/robsalz/torch/install/share/lua/5.1/nn/LogSoftMax.lua:4: attempt to call field &apos;LogSoftMax_updateOutput&apos; (a nil value)
stack traceback:
    ...rs/robsalz/torch/install/share/lua/5.1/nn/LogSoftMax.lua:4: in function &apos;updateOutput&apos;
    ...rs/robsalz/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function &apos;forward&apos;
    ...lz/torch/install/share/lua/5.1/nn/StochasticGradient.lua:35: in function &apos;f&apos;
    [string &quot;local f = function() return trainer:train(tra...&quot;]:1: in main chunk
    [C]: in function &apos;xpcall&apos;
    /Users/robsalz/torch/install/share/lua/5.1/itorch/main.lua:179: in function &lt;/Users/robsalz/torch/install/share/lua/5.1/itorch/main.lua:143&gt;
    /Users/robsalz/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function &apos;poll&apos;
    ...s/robsalz/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function &apos;poll&apos;
    ...s/robsalz/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function &apos;sleep_ex&apos;
    ...s/robsalz/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function &apos;start&apos;
    /Users/robsalz/torch/install/share/lua/5.1/itorch/main.lua:350: in main chunk
    [C]: in function &apos;require&apos;
    (command line):1: in main chunk
    [C]: at 0x010a62bbd0</pre>

<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">

**Comment by RobSalzwedel** [comment]
Reinstalling `nn`, and `cunn` seems to have done the trick for anyone encountering this problem again:

`luarocks install nn`
`luarocks install cunn`

**Comment by salman1993** [comment]
This happened to me twice before.
Why do we need to reinstall it? And how do I recongnize this problem?
Plus reinstalling is a hassle because for some reason, I had to uninstall Torch and reinstall it and install all the packages again.

It's happened again and reinstall didn't work. Opened a new issue for this as well.

```
Channel 1, Mean: 125.83175029297
Channel 1, Standard Deviation: 63.143400842609
Channel 2, Mean: 123.26066621094
Channel 2, Standard Deviation: 62.369209019002
Channel 3, Mean: 114.03068681641
Channel 3, Standard Deviation: 66.965808411114
# StochasticGradient: training
# current error = 2.2234263599277
# current error = 1.88329374547
# current error = 1.6842083223224
# current error = 1.5661180615187
# current error = 1.4682321660876
# StochasticGradient: you have reached the maximum number of iterations
# training error = 1.4682321660876
/home/s43moham/torch/install/bin/luajit: /home/s43moham/torch/install/share/lua/5.1/nn/Container.lua:67:
In 1 module of nn.Sequential:
/home/s43moham/torch/install/share/lua/5.1/nn/THNN.lua:110: bad argument #3 to 'v' (cannot convert 'struct THCudaTensor *' to 'struct THDoubleTensor *')
stack traceback:
    [C]: in function 'v'
    /home/s43moham/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
    ...am/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:96: in function <...am/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:92>
    [C]: in function 'xpcall'
    /home/s43moham/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
    ...e/s43moham/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    torchCudaTutorial.lua:82: in main chunk
    [C]: in function 'dofile'
    ...oham/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
    [C]: in function 'error'
    /home/s43moham/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
    ...e/s43moham/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    torchCudaTutorial.lua:82: in main chunk
    [C]: in function 'dofile'
    ...oham/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
```
