### ISSUE TITLE
Nonlinearities missing between Linear layers in "Deep Learning with Torch: the 60-minute blitz"

### ISSUE THREAD

**Issue by nkait** [soumith/cvpr2015#6]
Hi,
in [Deep Learning with Torch: the 60-minute blitz](https://github.com/soumith/cvpr2015/blob/master/Deep%20Learning%20with%20Torch.ipynb) a network is constructed which (I understand) is meant to imitate Lenet-5. However, there are no nonlinearities applied between the final linear layers:

```
net:add(nn.Linear(16*5*5, 120))             -- fully connected layer (matrix multiplication between input and weights)
net:add(nn.Linear(120, 84))
net:add(nn.Linear(84, 10))                   -- 10 is the number of outputs of the network (in this case, 10 digits)
```

which defeats the purpose of having multiple layers, as the result of stacking linear layers is still a linear function of the input. Even if the goal isn't to exactly replicate Lenet-5, omitting the nonlinearities entirely will probably be confusing to readers - after seeing this snippet, I thought that perhaps nn.Sequential applies some default nonlinearity after each layer, but that doesn't seem to be the case.

I'm still learning Torch, so I might be wrong, but I think that the following snippet would be better:

```
net:add(nn.Linear(16*5*5, 120))             -- fully connected layer (matrix multiplication between input and weights)
net:add(nn.Sigmoid())
net:add(nn.Linear(120, 84))
net:add(nn.Sigmoid())
net:add(nn.Linear(84, 10))                   -- 10 is the number of outputs of the network (in this case, 10 digits)
```

Any thoughts on this?

**Comment by soumith** [comment]
I didn't want to introduce too many things, so I didn't put non-linearities. I didn't realize it'll have the opposite confusing effect. I can fix it.

**Comment by soumith** [comment]
fixed in trunk.
