### ISSUE TITLE
itorch image not displaying images

### ISSUE THREAD

**Issue by wcarvalho** [soumith/cvpr2015#7]
Hello,

when I use the following:

> local screens = {}
> for i=1,36 do
>     local screen, reward, terminal = game_env:step(game_actions[torch.random(3)])
>     table.insert(screens, screen[1]:clone())
> end
> itorch.image(screens)

A blank screen as follows appears, not the screens from the game.

![download](https://cloud.githubusercontent.com/assets/6220222/12591428/8ed1d53e-c41c-11e5-9c70-7ec937be55c5.png)

**Comment by soumith** [comment]
what was the issue? I was clueless...

**Comment by wcarvalho** [comment]
It was my rom. It was leading Alewrap to get illegal instructions so the game never actually started. I found a good rom online but anything that I download from

> http://atariage.com/software_search.php?SystemID=2600

causes qlua to segfault. Can you recommend a repository to download files from? I've been testing files at random. Maybe not all games are supported?

Here's a sample segfault.

[segfault.txt](https://github.com/soumith/cvpr2015/files/107413/segfault.txt)

**Comment by soumith** [comment]
I dont know much about the atari stuff. You could try asking in https://github.com/deepmind/xitari or https://github.com/deepmind/alewrap

**Comment by wcarvalho** [comment]
Thank you
